name: nba-regression
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - requests
  - jupyter
  - pip
  - pip:
      - nba_api
      - xgboost
      - lightgbm
